language: python

python:
    - "pypy"
    - "3.5.0b3"
    - "3.4"
    - "3.3"
    - "2.7"
    - "2.6"

matrix:
  include:
    - python: "2.7"
      env: TOX_ENV=docs
      install: pip install tox
      script: tox -e $TOX_ENV

install: python setup.py develop

script: python setup.py nosetests

notifications:
    irc:
        channels:
            - "ircs://irc.megworld.co.uk:9000#inboxen"
        use_notice: true

sudo: false
