language: python

python:
    - "pypy"
    - "2.7"
    - "2.6"

install: python setup.py develop

before_script:
    - mkdir logs run
    - python -c "from salmon import commands; commands.main()" log --pid "./log.pid" --port 8899

script: python setup.py test

after_script: python -c "from salmon import commands; commands.main()" stop --pid "./log.pid"

notifications:
    irc:
        channels:
            - "ircs://irc.megworld.co.uk:9000#inboxen"
        use_notice: true

sudo: false
