language: python

python:
    - "pypy"
    - "2.7"
    - "2.6"

install: python setup.py develop

before_script:
    - mkdir logs run
    - ./bin/salmon log -pid "./log.pid" -port 8899

script: python setup.py test

after_script: ./bin/salmon stop -pid "./log.pid"

notifications:
    irc:
        channels:
            - "ircs://irc.megworld.co.uk:9000#inboxen"
        use_notice: true

sudo: false
